language: ruby

cache: bundler

services:
  - mysql

before_install:
  - gem install bundler -v 1.17.1

script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
